"""Create DashboardQueryResult

Revision ID: 7e7a49b90c5f
Revises: 4b4a97de5b7d
Create Date: 2023-03-03 01:32:47.575449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7a49b90c5f'
down_revision = '4b4a97de5b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_query_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('chatgpt_gql', sa.Text(), nullable=True),
    sa.Column('subgraph', sa.Text(), nullable=True),
    sa.Column('chain', sa.Text(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('gql_valid', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_query_result')
    # ### end Alembic commands ###
